import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header><h1>Header Container</h1></header>
        {children}
        {/* map over children for a "pageBuilder" effect
        use this in general to build pages quickly from simmilar parts */}
        <footer>
        <a href="#">
          <button>
            Back to top ^
          </button>
        </a>
        <p>footer area</p></footer>
      </body>
      
    </html>
  );
}
